

# charlie on -> luces living bajas
- action:
  - alias: Turn light down w charlie
    service: light.turn_on
    data:
      entity_id: group.Living
      transition: 5
      brightness: 1
  alias: CharlieLightsDown
  id: '1497921737529'
  trigger:
  - entity_id: media_player.Charlie
    from: 'off'
    platform: state
    to: playing
  - entity_id: media_player.Charlie
    from: idle
    platform: state
    to: playing
  - entity_id: media_player.Charlie
    from: paused
    platform: state
    to: playing


# charlie off -> luces living altas
- action:
  - alias: Turn light up w charlie
    service: light.turn_on
    data:
      entity_id: group.Living
      transition: 1
      brightness: 255
  alias: CharlieLightsUp
  id: '1497921737529'
  trigger:
  - entity_id: media_player.Charlie
    from: playing
    platform: state
    to: 'off'
  - entity_id: media_player.Charlie
    from: idle
    platform: state
    to: 'off'
  - entity_id: media_player.Charlie
    from: paused
    platform: state
    to: 'off'

# charlie paused -> luces living medias
- action:
  - alias: Turn light to mid w charlie paused
    service: light.turn_on
    data:
      entity_id: group.Living
      transition: 2
      brightness: 90
  alias: CharlieLightsMid
  id: '1497921737529'
  trigger:
  - entity_id: media_player.Charlie
    from: playing
    platform: state
    to: paused


# charlie on -> pushbullet
#- action:
#  - alias: Nico_pushbullet
#    service: notify.nicopushbullet
#    data:
#      message: Shhhh estoy viendo algo
#  alias: CharlieOn
#  id: '1497921737529'
#  trigger:
#  - entity_id: media_player.Charlie
#    from: 'off'
#    platform: state
#    to: playing
#  - entity_id: media_player.Charlie
#    from: idle
#    platform: state
#    to: playing



# speech "turn Charlie on" -> charlie on
- action:
  - alias: charlieOn
    service: media_player.play_media
    data:
      entity_id: media_player.Charlie
      media_id: https://www.youtube.com/watch?v=MDj5c15ja_s
      media_type: video
  trigger:
  - event_data:
      message: turn Charlie on
    event_type: conversation
    platform: event

# speech "turn living off" -> luces living off
- action:
  - alias: Turn off light with command
    service: light.turn_off
    data:
      entity_id: group.Living
      transition: 10
  trigger:
  - event_data:
      message: turn Living off
    event_type: conversation
    platform: event

# speech "turn living on" -> luces living on bajas
- action:
  - alias: Turn on light with command
    service: light.turn_on
    data:
      entity_id: group.Living
      transition: 10
      brightness: 2
  trigger:
  - event_data:
      message: turn Living on
    event_type: conversation
    platform: event
